# -*- coding: utf-8 -*-
"""password manager SAMRA FAROOQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZhCRY67HaWVIBth00eBf7-np_bg2tlgu
"""

import os
import json
import base64
import hashlib
import secrets
import string
import getpass

from cryptography.fernet import Fernet, InvalidToken


# ==========================================
# FILE SETTINGS
# ==========================================

VAULT_FILE = "password_vault.json"
MASTER_FILE = "master.key"


# ==========================================
# CREATE ENCRYPTION KEY
# ==========================================

def create_key(master_password):
    """
    Creates an encryption key from the master password.
    """

    key = hashlib.sha256(
        master_password.encode()
    ).digest()

    return base64.urlsafe_b64encode(key)


# ==========================================
# MASTER PASSWORD SETUP
# ==========================================

def setup_master_password():

    if os.path.exists(MASTER_FILE):
        return

    print("\nNo master password found.")
    print("Create a new master password.\n")

    while True:

        password = getpass.getpass(
            "Create master password: "
        )

        confirm = getpass.getpass(
            "Confirm master password: "
        )

        if password == confirm:

            if len(password) < 8:
                print(
                    "Password must contain at least 8 characters."
                )
                continue

            with open(MASTER_FILE, "w") as file:
                file.write(
                    hashlib.sha256(
                        password.encode()
                    ).hexdigest()
                )

            print("\nMaster password created successfully.")
            break

        else:
            print("Passwords do not match.")


# ==========================================
# VERIFY MASTER PASSWORD
# ==========================================

def verify_master_password():

    password = getpass.getpass(
        "Enter master password: "
    )

    with open(MASTER_FILE, "r") as file:
        stored_hash = file.read()

    entered_hash = hashlib.sha256(
        password.encode()
    ).hexdigest()

    if entered_hash == stored_hash:
        return password

    print("\nIncorrect master password.")
    return None


# ==========================================
# LOAD VAULT
# ==========================================

def load_vault(fernet):

    if not os.path.exists(VAULT_FILE):
        return []

    try:

        with open(VAULT_FILE, "r") as file:
            encrypted_data = file.read()

        decrypted_data = fernet.decrypt(
            encrypted_data.encode()
        )

        return json.loads(
            decrypted_data.decode()
        )

    except InvalidToken:

        print(
            "\nError: Unable to decrypt vault."
        )

        return []

    except json.JSONDecodeError:

        print(
            "\nError: Vault data is corrupted."
        )

        return []

    except Exception as error:

        print(
            f"\nError loading vault: {error}"
        )

        return []


# ==========================================
# SAVE VAULT
# ==========================================

def save_vault(vault, fernet):

    try:

        data = json.dumps(vault)

        encrypted_data = fernet.encrypt(
            data.encode()
        )

        with open(VAULT_FILE, "w") as file:
            file.write(
                encrypted_data.decode()
            )

        return True

    except Exception as error:

        print(
            f"\nError saving vault: {error}"
        )

        return False


# ==========================================
# ADD PASSWORD
# ==========================================

def add_password(vault):

    print("\n========== ADD PASSWORD ==========")

    website = input(
        "Website/Application: "
    ).strip()

    username = input(
        "Username/Email: "
    ).strip()

    password = getpass.getpass(
        "Password: "
    )

    if not website or not username or not password:

        print(
            "\nAll fields are required."
        )

        return

    entry = {
        "website": website,
        "username": username,
        "password": password
    }

    vault.append(entry)

    print(
        "\nPassword added successfully."
    )


# ==========================================
# VIEW PASSWORDS
# ==========================================

def view_passwords(vault):

    print("\n========== SAVED PASSWORDS ==========")

    if not vault:

        print("No passwords saved.")

        return

    for index, entry in enumerate(vault, start=1):

        print(f"\n[{index}]")
        print(
            f"Website  : {entry['website']}"
        )
        print(
            f"Username : {entry['username']}"
        )
        print(
            f"Password : {entry['password']}"
        )


# ==========================================
# SEARCH PASSWORD
# ==========================================

def search_password(vault):

    print("\n========== SEARCH ==========")

    search_text = input(
        "Enter website or username: "
    ).lower().strip()

    found = False

    for entry in vault:

        if (
            search_text in entry["website"].lower()
            or
            search_text in entry["username"].lower()
        ):

            print("\n------------------------")
            print(
                f"Website  : {entry['website']}"
            )
            print(
                f"Username : {entry['username']}"
            )
            print(
                f"Password : {entry['password']}"
            )

            found = True

    if not found:

        print(
            "\nNo matching password found."
        )


# ==========================================
# DELETE PASSWORD
# ==========================================

def delete_password(vault):

    print("\n========== DELETE PASSWORD ==========")

    if not vault:

        print("No passwords available.")

        return

    for index, entry in enumerate(vault, start=1):

        print(
            f"{index}. "
            f"{entry['website']} "
            f"({entry['username']})"
        )

    try:

        choice = int(
            input(
                "\nEnter password number to delete: "
            )
        )

        if choice < 1 or choice > len(vault):

            print("Invalid selection.")

            return

        deleted = vault.pop(choice - 1)

        print(
            f"\nDeleted password for "
            f"{deleted['website']}."
        )

    except ValueError:

        print(
            "Please enter a valid number."
        )


# ==========================================
# GENERATE STRONG PASSWORD
# ==========================================

def generate_password():

    print("\n========== PASSWORD GENERATOR ==========")

    try:

        length = int(
            input(
                "Enter password length: "
            )
        )

        if length < 8:

            print(
                "Password should be at least 8 characters."
            )

            return

        characters = (
            string.ascii_letters
            + string.digits
            + string.punctuation
        )

        password = "".join(
            secrets.choice(characters)
            for _ in range(length)
        )

        print(
            f"\nGenerated Password:\n{password}"
        )

    except ValueError:

        print(
            "Please enter a valid number."
        )


# ==========================================
# MAIN MENU
# ==========================================

def main():

    print("=" * 45)
    print("        SECURE PASSWORD MANAGER")
    print("=" * 45)

    # Create master password if first run
    setup_master_password()

    # Verify master password
    master_password = verify_master_password()

    if master_password is None:
        return

    # Create encryption key
    key = create_key(master_password)

    fernet = Fernet(key)

    # Load encrypted vault
    vault = load_vault(fernet)

    while True:

        print("\n")
        print("=" * 45)
        print("              MAIN MENU")
        print("=" * 45)

        print("1. Add Password")
        print("2. View Passwords")
        print("3. Search Password")
        print("4. Delete Password")
        print("5. Generate Strong Password")
        print("6. Exit")

        choice = input(
            "\nEnter your choice: "
        ).strip()

        if choice == "1":

            add_password(vault)

            save_vault(
                vault,
                fernet
            )

        elif choice == "2":

            view_passwords(vault)

        elif choice == "3":

            search_password(vault)

        elif choice == "4":

            delete_password(vault)

            save_vault(
                vault,
                fernet
            )

        elif choice == "5":

            generate_password()

        elif choice == "6":

            save_vault(
                vault,
                fernet
            )

            print(
                "\nVault saved securely."
            )

            print(
                "Thank you for using Password Manager."
            )

            break

        else:

            print(
                "\nInvalid choice. Please try again."
            )


# ==========================================
# PROGRAM START
# ==========================================

if __name__ == "__main__":
    main()